### PR TITLE
Improve splitting model

### PR DESCRIPTION
**Pull request by mvd-ows**
- Handle TCP/non-TCP sockets at different WFP layers and using different redirect callouts.
- Examine remote address for attempted connections on TCP sockets and infer whether they need to be rewritten.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 19 of 19 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: all files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[src/firewall/callouts.cpp, line 448 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1wYt3QNp9dXFQxOY:-MaY1wYt3QNp9dXFQxOZ:b-jrtep9) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L448)):*
> ```cpp
> LocalAddress(const IN6_ADDR *addr)
> {
> 	return IN6_IS_ADDR_LOOPBACK(addr) // ::1/128
> ```

Is this missing [ULAs](https://en.wikipedia.org/wiki/Unique_local_address)?
___
*[src/firewall/callouts.cpp, line 451 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1V_WDLTK4ggYD4Mq:-MaXz89h7apERvl4TMAS:bocwlwc) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L451)):*
> ```cpp
> 		|| IN6_IS_ADDR_LINKLOCAL(addr) // fe80::/10
> 		|| IN6_IS_ADDR_SITELOCAL(addr) // fec0::/10
> 		|| IN6_IS_ADDR_MULTICAST(addr) // ff00::/8
> ```

Is it correct to include ranges that are [routable](https://en.wikipedia.org/wiki/Multicast_address#IPv6) over the internet?
___
*[src/firewall/callouts.cpp, line 627 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY6I0M2Ha4dygAHuXu:-MaY6I0NEY_93AcCvf49:b-eeeuby) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L627)):*
> ```cpp
>             DbgPrint("Aborting connection processing because already redirected by us\n");
> 
>             goto Cleanup_data;
> ```

Could setting the action to `FWP_ACTION_CONTINUE` here undo the previous block?
___
*[src/firewall/pending.cpp, line 421 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaXQ_26CfN3H-PGm1OX:-MaXQ_27ABM5tcRXiFVp:b-61l16y) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/pending.cpp#L421)):*
> ```cpp
>     if (!AssertCompatibleLayer(LayerId))
>     {
>         return STATUS_INVALID_LEVEL;
> ```

In general, this status seems to be used for incorrect IRQ levels. Not important.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[src/firewall/callouts.cpp, line 448 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1wYt3QNp9dXFQxOY:-MaYC7NnALUsuGbQp8HU:b-gn7wk7) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L448)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this missing [ULAs](https://en.wikipedia.org/wiki/Unique_local_address)?
</blockquote></details>

Yep, adding `fd00::/8`.
___
*[src/firewall/callouts.cpp, line 451 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1V_WDLTK4ggYD4Mq:-MaYEQnq6I0MtOUaYKoF:btlk7fn) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L451)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is it correct to include ranges that are [routable](https://en.wikipedia.org/wiki/Multicast_address#IPv6) over the internet?
</blockquote></details>

Right, should we mask the second byte and verify the scope not to be `Global`?
___
*[src/firewall/callouts.cpp, line 627 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY6I0M2Ha4dygAHuXu:-MaYGD4YCIUkWtftkZgx:bmsz9rd) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L627)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could setting the action to `FWP_ACTION_CONTINUE` here undo the previous block?
</blockquote></details>

Interesting discussion.

The scenario is, some other callout that came before us, in this same layer, applied a soft block as its classification?

It's not entirely clear from documentation how the struct is being used when there are multiple callouts. But I imagine there's a single source of truth which is copied and provided for each callout to inspect and update. And sometimes, under the right conditions, the updated struct is then used to overwrite the single source.

And the single source holds the final verdict once all processing has completed.

In which case setting the action to `FWP_ACTION_CONTINUE` would have no effect. Because the logic which analyzes a callouts output should not allow `continue` to overwrite `block`, IMO.

What's your take on this?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[src/firewall/pending.cpp, line 421 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaXQ_26CfN3H-PGm1OX:-MaYL_yE7Q0q4c-z6iMb:b955ose) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/pending.cpp#L421)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

In general, this status seems to be used for incorrect IRQ levels. Not important.
</blockquote></details>

Yeah.. that's a problem with status codes. There's never one that matches exactly what you're trying to express.

Should I change this statement to use the generic `STATUS_UNSUCCESSFUL`?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[src/firewall/callouts.cpp, line 448 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1wYt3QNp9dXFQxOY:-MaYXwAy2HMgmVePSmDG:b-896fix) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L448)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Yep, adding `fd00::/8`.
</blockquote></details>

Done.
___
*[src/firewall/callouts.cpp, line 451 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1V_WDLTK4ggYD4Mq:-MaYY-DY5c-OjB5b2kce:b-896fix) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L451)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Right, should we mask the second byte and verify the scope not to be `Global`?
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[src/firewall/callouts.cpp, line 448 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1wYt3QNp9dXFQxOY:-MaYe8X6D--oCsiRW9P1:b-4kzasd) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L448)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I seriously doubt that it will matter, but couldn't all of `fc00::/7` be included? I.e. `((a->s6_bytes[0] & 0xfc) == 0xfc)`.
___
*[src/firewall/callouts.cpp, line 627 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY6I0M2Ha4dygAHuXu:-MaYfabOBom394nETWWD:b66pmhe) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L627)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Interesting discussion.

The scenario is, some other callout that came before us, in this same layer, applied a soft block as its classification?

It's not entirely clear from documentation how the struct is being used when there are multiple callouts. But I imagine there's a single source of truth which is copied and provided for each callout to inspect and update. And sometimes, under the right conditions, the updated struct is then used to overwrite the single source.

And the single source holds the final verdict once all processing has completed.

In which case setting the action to `FWP_ACTION_CONTINUE` would have no effect. Because the logic which analyzes a callouts output should not allow `continue` to overwrite `block`, IMO.

What's your take on this?
</blockquote></details>

Sounds reasonable. That makes me wonder: Do we want to override soft blocks? It looks like we currently set the action to "hard permit" in that case. But I trust that this makes sense.

I think I am actually confused about the recursion point. `CalloutClassifyConnect` returns when `FWPS_RIGHT_ACTION_WRITE` is not set, so how could one end up here again after a hard permit?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[src/firewall/callouts.cpp, line 448 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY1wYt3QNp9dXFQxOY:-MaZ1lr3DsfJhUfmX1tU:bmqkyxg) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L448)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I seriously doubt that it will matter, but couldn't all of `fc00::/7` be included? I.e. `((a->s6_bytes[0] & 0xfc) == 0xfc)`.
</blockquote></details>

Rules/usage surrounding that half of the block is undefined, so I don't think we want to include it.

`The block with L = 0, or globally assigned addresses, fc00::/8 is currently undefined. It was proposed that the allocation authority manage it, but this has not gained acceptance in the IETF.`
___
*[src/firewall/callouts.cpp, line 627 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/21#-MaY6I0M2Ha4dygAHuXu:-MaZ36tG0-9WFUg-nV9A:bq6sdog) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/32a3e8cafd36a8ca31358e55e5cfd7ee82151c15/src/firewall/callouts.cpp#L627)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Sounds reasonable. That makes me wonder: Do we want to override soft blocks? It looks like we currently set the action to "hard permit" in that case. But I trust that this makes sense.

I think I am actually confused about the recursion point. `CalloutClassifyConnect` returns when `FWPS_RIGHT_ACTION_WRITE` is not set, so how could one end up here again after a hard permit?
</blockquote></details>

For redirection, in the redirection layers, I don't think the classification is all that important. E.g. I wasn't able to block traffic by specifying either block/hard block in these layers.

Regarding overruling a soft block using a hard permit, this could be a problem in the auth layers. If a user has added filters on their own in an attempt to block certain traffic, the callouts may be overriding this traffic. I suggest we investigate this at a later time to prevent delaying the merge.

As for recursion, check the final argument here: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsapplymodifiedlayerdata0

The description is pretty useless, but sometimes, for some reasons, recursion occurs.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Pull request merged**
