### PR TITLE
Ipv6 first class

### PR DESCRIPTION
**Pull request by mvd-ows**
Add support for IPv6-only systems, and improve support for different combinations of IP interfaces on the adapters under consideration.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)* status: all files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[README.md, line 90 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUt2Gkj7ONkmoqY-jAe:-MUt2Gkj7ONkmoqY-jAf:bedssdx) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/README.md#L90)):*
> ```Markdown
> The following matrix describes the actions taken by the driver on excluded apps. The actions taken depend on which network interfaces are available.
> 
> |\#|Internet IPv4|Tunnel IPv4|Internet IPv6|Tunnel IPv6|Actions|
> ```

Can we support the case `Tunnel IPv4 && Internet IPv6`?
___
*[src/firewall/firewall.cpp, line 372 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUszUUEC_tgHxRxXm7Q:-MUszUUEC_tgHxRxXm7R:buk1oqj) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/firewall.cpp#L372)):*
> ```cpp
> 			return STATUS_SUCCESS;
> 		}
> 		case SPLITTING_MODE::MODE_2:
> ```

Suppose you had specific IPv6 routes going via some non-tunnel interface but no default route (or an analogous scenario). Wouldn't connections using these be blocked by WinFw? This is probably weird enough that it can be ignored.
___
*[src/firewall/mode.cpp, line 18 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUssAekCHOk_x-otCvi:-MUssAekCHOk_x-otCvj:bm8nck3) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/mode.cpp#L18)):*
> ```cpp
> 	const auto tunnelV6 = ip::ValidTunnelIpv6Address(IpAddresses);
> 
> 	if (internetV4 && tunnelV4 && internetV6 && tunnelV6)
> ```

Could this be simplified by using bits to represent each state in the enum, corresponding to the column in the readme? I.e.

```c++
enum class SPLITTING_MODE
{
    MODE_1 = 0b1111,
    MODE_2 = 0b1100,
    // ...
};


int mode = internetV4 << 3 | tunnelV4 << 2 | internetV6 << 1 | tunnelV6;

switch (mode)
{
    case SPLITTING_MODE::MODE_1:
    case SPLITTING_MODE::MODE_2:
    // ...
        *Mode = static_cast<SPLITTING_MODE>(mode);
        return STATUS_SUCCESS;
    default:
        return STATUS_INVALID_DISPOSITION;
}
```

Perhaps the modes could have more descriptive names as well. Such as `MODE_IT4IT6` instead of `MODE_1`, `MODE_IT4` instead of `MODE_2`, or `MODE_IT4I6` instead of `MODE_3`.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 90 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUt2Gkj7ONkmoqY-jAe:-MUxNTUg-DyL5dLw3Ef_:bb6un1j) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/README.md#L90)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can we support the case `Tunnel IPv4 && Internet IPv6`?
</blockquote></details>

Done
___
*[src/firewall/firewall.cpp, line 372 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUszUUEC_tgHxRxXm7Q:-MUxUD2ZCD9bWn4zU8wU:b-5t68d4) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/firewall.cpp#L372)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Suppose you had specific IPv6 routes going via some non-tunnel interface but no default route (or an analogous scenario). Wouldn't connections using these be blocked by WinFw? This is probably weird enough that it can be ignored.
</blockquote></details>

Yes and yes.

However, this is a user mode issue. The driver client is free to present any IPv6 interface as the primary IPv6 interface, regardless of routing.

In which case we would end up in `mode 3` instead and things would just work.
___
*[src/firewall/mode.cpp, line 18 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUssAekCHOk_x-otCvi:-MUxNe8M5tLDrpK4ptb6:b5yvh3a) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/mode.cpp#L18)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could this be simplified by using bits to represent each state in the enum, corresponding to the column in the readme? I.e.

```c++
enum class SPLITTING_MODE
{
    MODE_1 = 0b1111,
    MODE_2 = 0b1100,
    // ...
};


int mode = internetV4 << 3 | tunnelV4 << 2 | internetV6 << 1 | tunnelV6;

switch (mode)
{
    case SPLITTING_MODE::MODE_1:
    case SPLITTING_MODE::MODE_2:
    // ...
        *Mode = static_cast<SPLITTING_MODE>(mode);
        return STATUS_SUCCESS;
    default:
        return STATUS_INVALID_DISPOSITION;
}
```

Perhaps the modes could have more descriptive names as well. Such as `MODE_IT4IT6` instead of `MODE_1`, `MODE_IT4` instead of `MODE_2`, or `MODE_IT4I6` instead of `MODE_3`.
</blockquote></details>

This would be possible but I don't feel either suggestion adds that much.

One reason this is not suitably represented using bits is that an action may require to be implemented differently depending on the mode. Actions are not discrete items which can be freely combined. Compare e.g. `mode 1` and `mode 3`: The action `permit non-tunnel IPv6` is implemented differently.

Of course, actions != mode so the above is a rather weak argument.

The names you suggest are compressed. `mode 1` could be `MODE_I4T4I6T6` but even then, it doesn't mean much. One would still have to refer to the table of modes to understand which actions are suitable for a given mode. Hence why I prefer completely opaque names for this.

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[README.md, line 90 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUt2Gkj7ONkmoqY-jAe:-MUy4l1r2BnIhWIJBtIK:btojbfd) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/README.md#L90)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Done
</blockquote></details>

Great!
___
*[src/firewall/firewall.cpp, line 372 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUszUUEC_tgHxRxXm7Q:-MUxzLu92QonGIdUh_-d:b-hd3nrc) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/firewall.cpp#L372)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Yes and yes.

However, this is a user mode issue. The driver client is free to present any IPv6 interface as the primary IPv6 interface, regardless of routing.

In which case we would end up in `mode 3` instead and things would just work.
</blockquote></details>

Is there any way for the client to pick an appropriate interface if there is no default route?

Destination A might use interface X, and destination B interface Y. If you give the driver the address of X, I think connecting to B will cause the bind to be moved to X anyway, unless the socket is explicitly bound to Y. (Haven't checked.)

Anyway, this is unlikely to make any difference
___
*[src/firewall/mode.cpp, line 18 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUssAekCHOk_x-otCvi:-MUy5ccI7BMpGokHpw4Y:b-11hobi) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/mode.cpp#L18)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This would be possible but I don't feel either suggestion adds that much.

One reason this is not suitably represented using bits is that an action may require to be implemented differently depending on the mode. Actions are not discrete items which can be freely combined. Compare e.g. `mode 1` and `mode 3`: The action `permit non-tunnel IPv6` is implemented differently.

Of course, actions != mode so the above is a rather weak argument.

The names you suggest are compressed. `mode 1` could be `MODE_I4T4I6T6` but even then, it doesn't mean much. One would still have to refer to the table of modes to understand which actions are suitable for a given mode. Hence why I prefer completely opaque names for this.
</blockquote></details>

Alright.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[src/firewall/firewall.cpp, line 372 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/7#-MUszUUEC_tgHxRxXm7Q:-MUyTwH26zXo6F3esbae:ba5rpi0) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/5a8dec31d85ac19152badafcc8cf22cc8801f2fa/src/firewall/firewall.cpp#L372)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is there any way for the client to pick an appropriate interface if there is no default route?

Destination A might use interface X, and destination B interface Y. If you give the driver the address of X, I think connecting to B will cause the bind to be moved to X anyway, unless the socket is explicitly bound to Y. (Haven't checked.)

Anyway, this is unlikely to make any difference
</blockquote></details>

Yeah I don't think it can be solved generically. But this is uncommon enough that we shouldn't have to consider it further.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Pull request merged**
