### PR TITLE
External review phase1

### PR DESCRIPTION
**Pull request by mvd-ows**
As above.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Review by dlon — APPROVED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[src/trace.h, line 15 at r2](https://reviewable.io/reviews/mullvad/win-split-tunnel/18#-MZmcvXvBTB3OJJAbBr6:-MZmcvXvBTB3OJJAbBr7:b-2uykrb) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/2c394267881c4fd42bdcbe09f630cb94027aa859/src/trace.h#L15)):*
> ```objc
>         )                             
> 
> #define WPP_FLAG_LEVEL_LOGGER(flag, level)                             \
> ```

Does this (and the next macro) do anything? I took *conditions* in WPP_*conditions*_LOGGER to refer to parameters in the trace function declarations, but I didn't see `fn(FLAG, LEVEL, ...)` anywhere.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[src/trace.h, line 15 at r2](https://reviewable.io/reviews/mullvad/win-split-tunnel/18#-MZmcvXvBTB3OJJAbBr6:-MZnobLE6KtUyDCBe9Lz:b-ae9ggi) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/2c394267881c4fd42bdcbe09f630cb94027aa859/src/trace.h#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does this (and the next macro) do anything? I took *conditions* in WPP_*conditions*_LOGGER to refer to parameters in the trace function declarations, but I didn't see `fn(FLAG, LEVEL, ...)` anywhere.
</blockquote></details>

Well spotted! I can't say for sure what these macros are needed for. How are you able to determine that they're not needed?

Removing this and the next macro has no negative effect on the current code.

However, these macros seem to always be included for some type of Visual Studio generated driver project. Searching Github there are about 1300 matches in different repos.

We can of course remove the definitions and add them back as the need arises?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[src/trace.h, line 15 at r2](https://reviewable.io/reviews/mullvad/win-split-tunnel/18#-MZmcvXvBTB3OJJAbBr6:-MZqIRB2E6s_zxk5QZcw:b-ql1zsu) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/2c394267881c4fd42bdcbe09f630cb94027aa859/src/trace.h#L15)):*
If that's the case, then let's just keep them.

I only based my question on this:

> Each trace message function that you use must have a corresponding pair of macros. These macros identify the trace provider and specify the conditions that generate the messages. You typically define a pair of macros, WPP\_\<condition\>\_LOGGER and WPP\_\<condition\>\_ENABLED in terms of the default WPP\_LEVEL\_ENABLED and WPP\_LEVEL\_LOGGER macros.

https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-wpp-software-tracing-to-a-windows-driver

> ```
> // FUNC TraceEvents(LEVEL, FLAGS, MSG, ...);
> // FUNC DbgPrint{LEVEL=TRACE_LEVEL_INFORMATION, FLAGS=TRACE_GENERAL}(MSG, ...);
> ```
This implies that macros `WPP_LEVEL_FLAGS_LOGGER` and `WPP_LEVEL_FLAGS_ENABLED` need to be defined.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Pull request merged**
