### PR TITLE
Big review

### PR DESCRIPTION
**Pull request by mvd-ows**
-

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 31 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: 31 of 72 files reviewed, 7 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[build.bat, line 13 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSb7dha9jUpcF_5vnud:-MSb7dha9jUpcF_5vnue:b-ngvwbk) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/build.bat#L13)):*
> ```Batchfile
> :: Register "x64 Native Tools" environment
> 
> call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
> ```

Doesn't this assume you're using VS Community? Also, if you simply run the script from "x64 Native Tools Command Prompt", you probably don't need this.
___
*[src/mullvad-split-tunnel.vcxproj.user, line 1 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSbWijA66pnx8qM3kXU:-MSbWijA66pnx8qM3kXV:b-goa1pq) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/mullvad-split-tunnel.vcxproj.user#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

This file is excluded by `.gitignore`. That seems strange since it is in the repo at the same time.
___
*[src/containers/procregistry.cpp, line 98 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSb9tL62ZXGrsONyl1r:-MSYP70F3m6My0TtI02V:bvlfox2) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/containers/procregistry.cpp#L98)):*
> ```cpp
> 	auto parentEntry = (PROCESS_REGISTRY_ENTRY*)Context;
> 
> 	if (Entry->ParentEntry == parentEntry)
> ```

If `GetParentEntry` has not been called for `Entry`, then `Entry->ParentProcessId` will not be zeroed here. If `GetParentEntry` is then called at some later point, might the wrong parent be assigned if the pid has been recycled?

It only seems possible for this to occur if the processes are started before entering the engaged state. If in the engaged state, `EvaluateSplitting` will assign a parent node to the element. But otherwise (e.g., if the internet interface is down), the parent process can "depart" without this pid being reset. When `SyncProcessRegistry` is later run, the former child may be assigned a different process as parent.
___
*[src/containers/procregistry.cpp, line 367 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYSMuW25iCb5wtfypL:-MSYSMuW25iCb5wtfypM:bdmk183) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/containers/procregistry.cpp#L367)):*
> ```cpp
> )
> {
> 	return NULL == RtlEnumerateGenericTableAvl(&Context->Tree, TRUE);
> ```

Could this be `RtlIsGenericTableEmptyAvl`?
___
*[src/firewall/firewall.cpp, line 533 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYiMvnD4xJ1dihQxkv:-MSYiMvnD4xJ1dihQxkw:byjxkk) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L533)):*
> ```cpp
> 	if (blockIpv6)
> 	{
> 		status = blocking::RegisterFilterBlockSplitAppsIpv6Tx(Context->BlockingContext);
> ```

In principle, you could have no reachable IPv4 routes, only IPv6. Eventually, this case should probably be handled as well (instead of failing to engage).
___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MSYd76dBPdOHpg-UE8E:b-85f2le) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
> ```cpp
> 
> NTSTATUS
> TransactionAbort
> ```

If this fails, then `Context->Transaction.Lock` will not be released. Currently, if aborting fails, the error is only logged at the call sites, which means that there there will be a deadlock at the next new transaction.

I don't think that this is news. The agreement, I think, was that it isn't really possible to handle this outcome. Would it make sense to repeat `TransactionAbort` in a loop until it succeeds?
___
*[src/procmgmt/procmgmt.cpp, line 17 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYQ0Ko66LIq-8GnsHn:-MSYQ0Ko66LIq-8GnsHo:b-8dvyat) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/procmgmt/procmgmt.cpp#L17)):*
> a a
___
*[src/procmgmt/procmgmt.cpp, line 62 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYQYl00V-GgKlQ_zdK:-MSYQYl00V-GgKlQ_zdL:b-610num) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/procmgmt/procmgmt.cpp#L62)):*
> ```cpp
>     //
> 
> 	const auto equalBytes = RtlCompareMemory
> ```

This doesn't seem to rule out the possibility that `existingEntry->ImageName` is longer than `newEntry->ImageName`.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: 31 of 72 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[build.bat, line 13 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSb7dha9jUpcF_5vnud:-MSc9QeZ1DjhCsCoKh-E:btj4ms) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/build.bat#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Doesn't this assume you're using VS Community? Also, if you simply run the script from "x64 Native Tools Command Prompt", you probably don't need this.
</blockquote></details>

That's a good point. Let me see if there's some environment variable that would indicate the environment is configured and ready. And if the variable isn't present we abort.
___
*[src/mullvad-split-tunnel.vcxproj.user, line 1 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSbWijA66pnx8qM3kXU:-MSc9yGr0fyoIyW0VyP0:b-tfoqgz) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/mullvad-split-tunnel.vcxproj.user#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This file is excluded by `.gitignore`. That seems strange since it is in the repo at the same time.
</blockquote></details>

Well spotted. This is because the default signing action for a driver project is to sign using a test certificate. So the build will fail until you update the project with a certificate thumbprint.

For a freshly cloned repository, I prefer seeing the build succeed.
___
*[src/containers/procregistry.cpp, line 98 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSb9tL62ZXGrsONyl1r:-MScLXOf-GVkI3KCDkWg:bdwopyf) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/containers/procregistry.cpp#L98)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If `GetParentEntry` has not been called for `Entry`, then `Entry->ParentProcessId` will not be zeroed here. If `GetParentEntry` is then called at some later point, might the wrong parent be assigned if the pid has been recycled?

It only seems possible for this to occur if the processes are started before entering the engaged state. If in the engaged state, `EvaluateSplitting` will assign a parent node to the element. But otherwise (e.g., if the internet interface is down), the parent process can "depart" without this pid being reset. When `SyncProcessRegistry` is later run, the former child may be assigned a different process as parent.
</blockquote></details>

Excellent catch!

I wonder why the assert below isn't used as the actual condition instead.

I'll change the `Context` argument to hold the PID of the departing process instead.

Sounds good?
___
*[src/containers/procregistry.cpp, line 367 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYSMuW25iCb5wtfypL:-MScNukwDUijM6JxNPGj:btvm5a7) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/containers/procregistry.cpp#L367)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could this be `RtlIsGenericTableEmptyAvl`?
</blockquote></details>

Certainly could, and in fact should be.
___
*[src/firewall/firewall.cpp, line 533 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYiMvnD4xJ1dihQxkv:-MScR1cJ0AAO94ProRKB:b3d6e56) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L533)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

In principle, you could have no reachable IPv4 routes, only IPv6. Eventually, this case should probably be handled as well (instead of failing to engage).
</blockquote></details>

Yep, good point. Currently it that were to happen, execution would not reach the current function. You can refer `ioctl::VpnActive()`, but you know this already.

This seemed like a reasonable design considering that all relays are accessed using IPv4. That will surely change at some point, but this implementation should suffice for now?
___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MScVctS9vCyQZF7o4Re:b-qlzshh) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If this fails, then `Context->Transaction.Lock` will not be released. Currently, if aborting fails, the error is only logged at the call sites, which means that there there will be a deadlock at the next new transaction.

I don't think that this is news. The agreement, I think, was that it isn't really possible to handle this outcome. Would it make sense to repeat `TransactionAbort` in a loop until it succeeds?
</blockquote></details>

Well, there's just no way of winning if `FwpmTransactionAbort0`fails.

I don't think looping would be preferable because it's not likely to succeed at some later point in time, either. The only potential advantage is that a core would be consumed by the spinning so the user might be able to notice something is wrong.

Really, the best thing one can do is write an entry to the Windows eventlog and call `KeBugCheck`. But we've managed to avoid `KeBugCheck` this far...
___
*[src/procmgmt/procmgmt.cpp, line 62 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYQYl00V-GgKlQ_zdK:-MScest26pgywjWUpJNw:b6l1miz) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/procmgmt/procmgmt.cpp#L62)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This doesn't seem to rule out the possibility that `existingEntry->ImageName` is longer than `newEntry->ImageName`.
</blockquote></details>

Thanks. Corrected the code and consolidated all similar comparisons as well.

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 22 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: 52 of 72 files reviewed, 5 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[.gitignore, line 1 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSghRrZ0ojVpwuHLjmh:-MSghRr_7R9lhK8UzjGp:b-cucwqw) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/.gitignore#L1)):*
> ```ignore
> /bin/
> ```

`resource.aps` could probably be included here.
___
*[src/ioctl.cpp, line 126 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSh4AId9m_5lJ2vCZye:-MSgpYytD2uH_QcoiSeY:btv0ozt) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/ioctl.cpp#L126)):*
> ```cpp
>     {
>         Entry->TargetSettings.Split = ST_PROCESS_SPLIT_STATUS_ON_BY_INHERITANCE;
>     }
> ```

Won't this mean that a child will no longer be excluded if the parent has not departed, even if the imagename of the parent is still included in the config?
___
*[src/ioctl.cpp, line 379 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSh2HRD1qAvwfTfpt5o:-MSh2HRD1qAvwfTfpt5p:btsi6c) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/ioctl.cpp#L379)):*
> ```cpp
> bool
> NTAPI
> ClearApplySplitSetting
> ```

This is never used.
___
*[src/firewall/firewall.cpp, line 533 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYiMvnD4xJ1dihQxkv:-MShn3uU9qvy1ZE7Icqh:bn16gwo) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L533)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Yep, good point. Currently it that were to happen, execution would not reach the current function. You can refer `ioctl::VpnActive()`, but you know this already.

This seemed like a reasonable design considering that all relays are accessed using IPv4. That will surely change at some point, but this implementation should suffice for now?
</blockquote></details>

There's no rush. It won't be too long before the app is usable in this scenario, though. I think that means that supposedly excluded processes will be tunneled (driver will leave the engaged state), but this will not be obvious to the user.

Should this be prevented in userspace? I.e., by failing to connect if split tunneling is enabled and there is no default IPv4 route (and disconnecting if an existing IPv4 route is removed).

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: 52 of 72 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[.gitignore, line 1 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSghRrZ0ojVpwuHLjmh:-MSle7Kk5YOaad4i0Ic7:bxpaqdp) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/.gitignore#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`resource.aps` could probably be included here.
</blockquote></details>

Well, yes. I'll add it but it shouldn't be necessary.

`*.aps` is generated when editing `*.rc` in the Visual Studio resource editor, something which you should not be doing with the current `resource.rc`.

The current version resource is hand-crafted and might not be compatible with the resource editor.
___
*[src/ioctl.cpp, line 126 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSh4AId9m_5lJ2vCZye:-MSliQLx-LKLKCZGttY3:b-t31iym) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/ioctl.cpp#L126)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Won't this mean that a child will no longer be excluded if the parent has not departed, even if the imagename of the parent is still included in the config?
</blockquote></details>

Only momentarily, and only in settings data that is still being prepared.

This function is followed up by traversing the process tree again and applying `PropagateApplyTargetSettings()`.
___
*[src/ioctl.cpp, line 379 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSh2HRD1qAvwfTfpt5o:-MSmP-UE23g0oedOO8-V:bk6l5n1) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/ioctl.cpp#L379)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is never used.
</blockquote></details>

Great find. Looks like its been incorporated into either `ApplyFinalizeTargetSettings()` or `ClearRealizeAnnounceSettingsChange()`.
___
*[src/firewall/firewall.cpp, line 533 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYiMvnD4xJ1dihQxkv:-MSmQ5Vu4Cq5grH3nnVv:bc145kc) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L533)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There's no rush. It won't be too long before the app is usable in this scenario, though. I think that means that supposedly excluded processes will be tunneled (driver will leave the engaged state), but this will not be obvious to the user.

Should this be prevented in userspace? I.e., by failing to connect if split tunneling is enabled and there is no default IPv4 route (and disconnecting if an existing IPv4 route is removed).
</blockquote></details>

Well, the driver will only engage if there's a default IPv4 route to begin with. I think the scenario you're talking about is if the driver is engaged, and the routing changes such that there is now only a default IPv6 route? In that case the driver, upon learning about updated routing, would leave the engaged state.

Either we implement something along the lines of what you suggest, or we update the driver to support this scenario. I think we'd have to run this by @faern.

**Review by dlon — APPROVED** [review]
> Reviewed 20 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MSm73vm17hApeon1UBH:b-1jt7yx) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
> ```cpp
> 	ClassifyOut->rights &= ~FWPS_RIGHT_ACTION_WRITE;
> 
> 	if (Ipv4)
> ```

Could you use `INETADDR_SETLOOPBACK((PSOCKADDR)&(bindRequest->localAddressAndPort))` here, or is it explicit on purpose?
___
*[src/firewall/blocking.cpp, line 127 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm-_4Z0pfZ963yQ9zI:-MSm-_4_59BL2bH2zMrE:b2ejun0) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/blocking.cpp#L127)):*
> ```cpp
> 	}
> 
> 	InitializeListHead((LIST_ENTRY*)evt);
> ```

It might be a bit more consistent with other code to access the entry via `&evt->ListEntry`.

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)

___
*[src/firewall/splitting.cpp, line 123 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MT1fIaJ3tcuSwOpP63o:-MT1fIaJ3tcuSwOpP63p:bupkq67) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/splitting.cpp#L123)):*
> ```cpp
> 			DbgPrint("SPLITTING\n");
> 
> 			bindTarget->sin_addr = Context->IpAddresses.Addresses.InternetIpv4;
> ```

As discussed on Slack: It seems excluded processes may be unable to connect to `localhost` if sockets are bound to `0.0.0.0` (i.e., `bindRequest->localAddressAndPort` is `0.0.0.0:*`). Should the function make sure that the destination address is not `localhost` before replacing the bind?

**Comment by mvd-ows** [comment]
___
*[src/firewall/splitting.cpp, line 123 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MT1fIaJ3tcuSwOpP63o:-MTAvzRx-zL8KHOsBaS5:bc1cw2w) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/splitting.cpp#L123)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

As discussed on Slack: It seems excluded processes may be unable to connect to `localhost` if sockets are bound to `0.0.0.0` (i.e., `bindRequest->localAddressAndPort` is `0.0.0.0:*`). Should the function make sure that the destination address is not `localhost` before replacing the bind?
</blockquote></details>

Implicit binds overall as well as explicit binds to `0.0.0.0` end up being redirected by the driver logic.

This affects excluded apps trying to connect to `127.0.0.1`, unless they explicitly bind the socket to localhost before connecting.

The destination address is unknown at the time of binding. We could possibly use "WFP connection redirection" to address this use case, but that's a whole other can of worms.

**Comment by mvd-ows** [comment]
___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MTBCOnW--kEWS5mBO7d:bstf869) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could you use `INETADDR_SETLOOPBACK((PSOCKADDR)&(bindRequest->localAddressAndPort))` here, or is it explicit on purpose?
</blockquote></details>

Hmm.. pretty sure I knew about that macro at the time of authoring this code. Can't really say why I didn't use it.

One difference is the macro also sets the port to 0. Could there be some reason not to clear the port?

**Comment by mvd-ows** [comment]
___
*[src/firewall/blocking.cpp, line 127 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm-_4Z0pfZ963yQ9zI:-MTBQZ1KD4eDbZ5koJ6f:b4y9qwc) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/blocking.cpp#L127)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It might be a bit more consistent with other code to access the entry via `&evt->ListEntry`.
</blockquote></details>

Done. Included next time the "fix" branch is pushed.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MTBRIMJ36W5otnBBp_X:b-buyma4) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Hmm.. pretty sure I knew about that macro at the time of authoring this code. Can't really say why I didn't use it.

One difference is the macro also sets the port to 0. Could there be some reason not to clear the port?
</blockquote></details>

Ah. You'll want to keep the port, especially if the socket accepts incoming connections.
___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MT1i5F0-qbZsEL4nKg-:b1q2z5a) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
`KeBugCheck` seems excessive. I don't expect the entire system to necessarily become unusable if this happens, so probably the error should just be logged and ignored. [MS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kebugcheckex):

> Whenever possible, all kernel-mode components should log an error and continue to run, rather than calling KeBugCheckEx.

**Comment by mvd-ows** [comment]
___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MTCg82kAA4d43LTSWoA:b-wd5jwv) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`KeBugCheck` seems excessive. I don't expect the entire system to necessarily become unusable if this happens, so probably the error should just be logged and ignored. [MS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kebugcheckex):

> Whenever possible, all kernel-mode components should log an error and continue to run, rather than calling KeBugCheckEx.
</blockquote></details>

What do you think is preferable between writing into the system event log, and raising an event on the channel that is already established with the daemon?

There's a good chance that events written to the system event log would go unnoticed?

**Comment by mvd-ows** [comment]
___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MTCh2UuAe2ZZtV_-Eyx:bqt8i5d) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Ah. You'll want to keep the port, especially if the socket accepts incoming connections.
</blockquote></details>

That may have been the reasoning I used, but the reasoning seems flawed.

If you consider the context... We want to move the bind to localhost and more than anything, we want to see it succeed. Not because we expect someone will be using the socket successfully, but because we want to lock/consume the socket.

Given this, setting the port to 0 makes the most sense?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)

___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MTFpEVP2aq4MmgdU9Fc:b-pbdqz3) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

That may have been the reasoning I used, but the reasoning seems flawed.

If you consider the context... We want to move the bind to localhost and more than anything, we want to see it succeed. Not because we expect someone will be using the socket successfully, but because we want to lock/consume the socket.

Given this, setting the port to 0 makes the most sense?

</blockquote></details>

Agreed.
___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MTFokqd6GG8jSAjQNhh:br2mqo7) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What do you think is preferable between writing into the system event log, and raising an event on the channel that is already established with the daemon?

There's a good chance that events written to the system event log would go unnoticed?
</blockquote></details>

If it's simpler to use the system event log, given that this error is unrecoverable and should never occur anyway, I think I favor that.

In general, might the system event log also be more reliable? E.g. if some unrecoverable error interferes with the driver's event system, then it may never be logged. In this specific case, that is probably not true. But that would maybe be another point in favor of the event log.

**Comment by mvd-ows** [comment]
___
*[src/firewall/asyncbind.cpp, line 51 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSm73vm17hApeon1UBG:-MTLN6n-75aD61CZ-vYU:b-ngr5j2) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/asyncbind.cpp#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Included with next push.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[src/firewall/firewall.cpp, line 903 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYd76cEaNSkck7waTH:-MTLhhqW8ekGyr03M5xJ:b-z0d5oz) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L903)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If it's simpler to use the system event log, given that this error is unrecoverable and should never occur anyway, I think I favor that.

In general, might the system event log also be more reliable? E.g. if some unrecoverable error interferes with the driver's event system, then it may never be logged. In this specific case, that is probably not true. But that would maybe be another point in favor of the event log.
</blockquote></details>

I'll track this as a separate task, OK? And schedule it to some time after this PR is closed.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[src/firewall/firewall.cpp, line 533 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MSYiMvnD4xJ1dihQxkv:-MTZddKq0rgZmPpqUq2h:byds3zb) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/firewall.cpp#L533)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Well, the driver will only engage if there's a default IPv4 route to begin with. I think the scenario you're talking about is if the driver is engaged, and the routing changes such that there is now only a default IPv6 route? In that case the driver, upon learning about updated routing, would leave the engaged state.

Either we implement something along the lines of what you suggest, or we update the driver to support this scenario. I think we'd have to run this by @faern.


</blockquote></details>

We'll update the driver; This is being tracked as a separate task.
___
*[src/firewall/splitting.cpp, line 123 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/2#-MT1fIaJ3tcuSwOpP63o:-MTZdsRME2idZviwNu0-:b-1l2ztj) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e2756e0093b1bfdec20834664c790e7274254600/src/firewall/splitting.cpp#L123)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Implicit binds overall as well as explicit binds to `0.0.0.0` end up being redirected by the driver logic.

This affects excluded apps trying to connect to `127.0.0.1`, unless they explicitly bind the socket to localhost before connecting.

The destination address is unknown at the time of binding. We could possibly use "WFP connection redirection" to address this use case, but that's a whole other can of worms.
</blockquote></details>

Documented as a limitation, for now.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Comment by mvd-ows** [comment]
All minor issues have been corrected and merged in a separate PR. A few larger issues are tracked separately. I'm closing this mock-PR.

**Pull request closed without merging**
