### PR TITLE
Add traffic leak tests

### PR DESCRIPTION
**Pull request by mvd-ows**
As above.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 10 unresolved discussions (waiting on @mvd-ows)

___
*[leaktest/leaktest.cpp, line 119 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWcquVM2NaBvLXBBKAK:-MWcquVN3vvEyj_KxX2I:b16znoi) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/leaktest.cpp#L119)):*
> ```cpp
> 	if (0 != WSAStartup(MAKEWORD(2, 2), &winSockData))
> 	{
> 		std::cout << "Failed to initialize winsock: " << FormatWsaError(WSAGetLastError()) << std::endl;
> ```

Could `stderr`/`cerr` be used for errors?
___
*[leaktest/README.md, line 45 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiyqzVCDkpTj51CL-X:-MWiyqzVCDkpTj51CL-Y:b-vd79no) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L45)):*
> ```Markdown
> `leaktest gen1 [tcp/udp] [delay-ms]`
> 
> ## Split tunnel tests
> ```

Would it also make sense to test whether it is possible to bind a socket to the tunnel interface, and send or receive data, in an already excluded app? (Obviously, this should fail.)
___
*[leaktest/README.md, line 57 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWcx_ubEdKJGtn9CZV3:-MWcx_ubEdKJGtn9CZV4:b2834ij) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L57)):*
> ```Markdown
> ### `st2`
> 
> Evaluate whether existing connections are blocked when an app becomes split.
> ```

Nitpick: It might be better to talk about "excluding" the app from the tunnel rather than "splitting" it. This was discussed at some point.
___
*[leaktest/README.md, line 79 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWixyBf49ay6w8e0gDP:-MWixyBf49ay6w8e0gDQ:b-en2etv) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L79)):*
> ```Markdown
> `leaktest st4`
> 
> ### `st5`
> ```

What do you think of also testing whether *existing* children and grandchildren are excluded when the testing app is excluded?

Maybe even the case where the first child (but not the grandchild) is killed before the parent is excluded. I can't remember if we even handle this case.
___
*[leaktest/sockutil.cpp, line 20 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiJNYD3WpuKZsCxWpO:-MWiJNYD3WpuKZsCxWpP:b-ap6i1j) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L20)):*
> ```cpp
> SOCKET CreateBindSocket(const IN_ADDR &ip, uint16_t port, bool tcp)
> {
> 	int type = SOCK_STREAM;
> ```

This could be shorter:
```c++
int type = tcp ? SOCK_STREAM : SOCK_DGRAM;
int protocol = tcp ? IPPROTO_TCP : IPPROTO_UDP;
```
Not sure if that's better, though.
___
*[leaktest/sockutil.cpp, line 92 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiJk5015YCX9mfqBky:-MWiJk5015YCX9mfqBkz:b-by0rre) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L92)):*
I think this is incorrect. `INVALID_SOCKET` should be [used](https://docs.microsoft.com/en-us/windows/win32/winsock/socket-data-type-2) instead:

> Windows Sockets handles have no restrictions, other than that the value INVALID_SOCKET is not a valid socket. Socket handles may take any value in the range 0 to INVALID_SOCKET–1.
___
*[leaktest/sockutil.cpp, line 199 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiLmhB9_60A-1LVrWH:-MWiLmhB9_60A-1LVrWI:b-o93u64) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L199)):*
> ```cpp
> 
> 		ss << L"Unexpected socket bind. Expected address " << IpToString(ip)
> 			<< ", Actual address " << IpToString(actualBind.sin_addr);
> ```

The second literal is missing an `L` prefix.
___
*[leaktest/sockutil.cpp, line 251 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiTvce2SKSYN07RCc5:-MWiTvce2SKSYN07RCc6:bu6vvr9) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L251)):*
> ```cpp
> }
> 
> WinsockOverlapped *AllocateWinsockOverlapped()
> ```

Wouldn't it be better to rely on RAII and return a `shared_ptr`? Or maybe create `shared_ptr`s at the call sites.
___
*[leaktest/sockutil.cpp, line 255 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiURFf0vXJiTack8Q7:-MWiURFf0vXJiTack8Q8:bruc6dv) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L255)):*
> ```cpp
> 	auto ctx = new WinsockOverlapped;
> 
> 	RtlZeroMemory(&ctx->overlapped, sizeof(ctx->overlapped));
> ```

Is `RtlZeroMemory` typically used in user-mode code? Doesn't matter as long as it works, though.
___
*[leaktest/util.cpp, line 93 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWihHHw6bvU-XI-oi8e:-MWihHHw6bvU-XI-oi8f:b-1wy1h9) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L93)):*
> ```cpp
> 	const std::wstring &path,
> 	const std::vector<std::wstring> &args,
> 	LPPROC_THREAD_ATTRIBUTE_LIST attributes
> ```

`attributes` could be `std::optional` or a pointer. Then you could just call `LaunchProcessWithAttributes` from `LaunchProcess` to avoid duplicating code.
___
*[leaktest/util.cpp, line 98 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWihqft2F6oBS0sblKq:-MWihqft2F6oBS0sblKr:b-2er60o) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L98)):*
> ```cpp
> 	const auto fspath = std::filesystem::path(path);
> 
> 	if (false == fspath.is_absolute()
> ```

Are these preconditions only expected for `LaunchProcessWithAttributes` and not `LaunchProcess`?
___
*[leaktest/util.cpp, line 287 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWitsG67QP2buJXB7ML:-MWitsG73drYOL_ASuWn:b-eb0gks) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L287)):*
> ```cpp
> 	sd += [&attributeList]()
> 	{
> 		DeleteProcThreadAttributeList((LPPROC_THREAD_ATTRIBUTE_LIST)&attributeList[0]);
> ```

Won't the list leak if `UpdateProcThreadAttribute` fails?
___
*[leaktest/util.cpp, line 392 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj3FzX8MtJoo34o09C:-MWj3FzX8MtJoo34o09D:b-jops7h) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L392)):*
> ```cpp
> }
> 
> std::wstring IpToString(const IN_ADDR &ip)
> ```

s/Ip/Ipv4?
___
*[leaktest/split-tunnel/st1.cpp, line 199 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj06Mo6lLUKm54nfV_:-MWj06Mo6lLUKm54nfVa:bf8i00w) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/split-tunnel/st1.cpp#L199)):*
> ```cpp
> 		std::cout << (char*)&buffer[0];
> 
> 		send(echoSocket, (char*)&buffer[0], (int)index, 0);
> ```

Should the return value not be checked?
___
*[leaktest/split-tunnel/st1.cpp, line 265 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj0USp4NUpX6cLImT3:-MWj0USp4NUpX6cLImT4:b-glibb2) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/split-tunnel/st1.cpp#L265)):*
> ```cpp
> 	std::cout << "Bind details: " << inet_ntoa(bindInfo.sin_addr) << ":" << ntohs(bindInfo.sin_port) << std::endl;
> 
> 	if (0 != serverAddr.compare(common::string::ToWide(inet_ntoa(bindInfo.sin_addr))))
> ```

Nitpick (here and elsewhere): Would it make more sense to parse `serverAddr` using `ParseIpv4`, and compare the result to `bindInfo`? Or at least use `IpToString(bindInfo.sin_addr)`.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 9 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[leaktest/leaktest.cpp, line 119 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWcquVM2NaBvLXBBKAK:-MWj8NZ2EKOAoQ2X0HqL:b-896fix) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/leaktest.cpp#L119)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could `stderr`/`cerr` be used for errors?
</blockquote></details>

Done.
___
*[leaktest/README.md, line 45 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiyqzVCDkpTj51CL-X:-MWjS3HP5j3UTXdNCBDf:b-16ydax) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L45)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it also make sense to test whether it is possible to bind a socket to the tunnel interface, and send or receive data, in an already excluded app? (Obviously, this should fail.)
</blockquote></details>

Well, it wouldn't fail. The bind would be redirected to the LAN-interface.

But you may be right, it could be useful to have a test case that performs the two essential tests:

In an excluded context:

- Create a socket which is not bound. Connect to wherever and verify that the socket has been bound to the LAN interface through bind redirection.
- Create a socket and bind it to the tunnel interface. Verify that the bind was redirected and that the socket has been bound to the LAN interface.
___
*[leaktest/README.md, line 57 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWcx_ubEdKJGtn9CZV3:-MWjWsVc5aGjRc8nD6Xf:b-896fix) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L57)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nitpick: It might be better to talk about "excluding" the app from the tunnel rather than "splitting" it. This was discussed at some point.
</blockquote></details>

Done.
___
*[leaktest/README.md, line 79 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWixyBf49ay6w8e0gDP:-MWjX9XZCWQnM4I_K4gp:b-5mypc) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L79)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What do you think of also testing whether *existing* children and grandchildren are excluded when the testing app is excluded?

Maybe even the case where the first child (but not the grandchild) is killed before the parent is excluded. I can't remember if we even handle this case.
</blockquote></details>

That's two separate scenarios The first one can be interesting to test for, I'll add a test for this.

The second one is non-trivial to support. In order to pull it off you'd have to monitor the entire process tree. I imagine few implementations besides ours do this. Then for each node, you'd have to store a reference to the closest relative.

In our implementation, we clear the parent information for a node if the parent exits. This is technically wrong, I suppose, but it keeps the logic simple and is easy to reason about.

Still think we should add a test for the second scenario?

**Review by dlon — COMMENTED** [review]
I resolved some threads but noticed there weren't any actual changes pushed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-:-MWx3EqT-YXgua-0vYZ-:b-tz79ay)* status: all files reviewed, 9 unresolved discussions (waiting on @mvd-ows)

___
*[leaktest/README.md, line 45 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiyqzVCDkpTj51CL-X:-MWwxzsw1clPL3qEnqOf:brxp9sq) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L45)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Well, it wouldn't fail. The bind would be redirected to the LAN-interface.

But you may be right, it could be useful to have a test case that performs the two essential tests:

In an excluded context:

- Create a socket which is not bound. Connect to wherever and verify that the socket has been bound to the LAN interface through bind redirection.
- Create a socket and bind it to the tunnel interface. Verify that the bind was redirected and that the socket has been bound to the LAN interface.
</blockquote></details>

Sounds good.
___
*[leaktest/README.md, line 79 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWixyBf49ay6w8e0gDP:-MWx2a_c5VV6koE_gZnJ:bsk87t) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/README.md#L79)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

That's two separate scenarios The first one can be interesting to test for, I'll add a test for this.

The second one is non-trivial to support. In order to pull it off you'd have to monitor the entire process tree. I imagine few implementations besides ours do this. Then for each node, you'd have to store a reference to the closest relative.

In our implementation, we clear the parent information for a node if the parent exits. This is technically wrong, I suppose, but it keeps the logic simple and is easy to reason about.

Still think we should add a test for the second scenario?
</blockquote></details>

No, I don't think it's necessary.

**Review by mvd-ows — COMMENTED** [review]
Yep, code wasn't ready to be submitted but I wanted to get the comments published.

> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-:-MWxH3Gt0jJuUZ5VBUdd:b-jrdunz)* status: all files reviewed, 9 unresolved discussions (waiting on @mvd-ows)

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[leaktest/sockutil.cpp, line 20 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiJNYD3WpuKZsCxWpO:-MWyjheI07Ve6YHzSVTX:bt2vr1b) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L20)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This could be shorter:
```c++
int type = tcp ? SOCK_STREAM : SOCK_DGRAM;
int protocol = tcp ? IPPROTO_TCP : IPPROTO_UDP;
```
Not sure if that's better, though.
</blockquote></details>

Fixed.
___
*[leaktest/sockutil.cpp, line 92 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiJk5015YCX9mfqBky:-MWyr0hSBC3TtlFV17VV:bl25hca) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L92)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think this is incorrect. `INVALID_SOCKET` should be [used](https://docs.microsoft.com/en-us/windows/win32/winsock/socket-data-type-2) instead:

> Windows Sockets handles have no restrictions, other than that the value INVALID_SOCKET is not a valid socket. Socket handles may take any value in the range 0 to INVALID_SOCKET–1.
</blockquote></details>

Fixed.

But the larger issue is if an uninitialized socket is passed into this function. Can't protect against or even detect that case using these primitive types.

Luckily this is not production code.
___
*[leaktest/sockutil.cpp, line 199 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiLmhB9_60A-1LVrWH:-MWyrdSrBYtm86_jucOO:bt2vr1b) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L199)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The second literal is missing an `L` prefix.
</blockquote></details>

Fixed.
___
*[leaktest/sockutil.cpp, line 255 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiURFf0vXJiTack8Q7:-MWysjJE8o14d0HqITi-:bghuy1y) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L255)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is `RtlZeroMemory` typically used in user-mode code? Doesn't matter as long as it works, though.
</blockquote></details>

`ZeroMemory` is documented as being an alias for `RtlZeroMemory`. So either is fine to use, but for consistency maybe we should always use `ZeroMemory` for user mode code?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[leaktest/sockutil.cpp, line 251 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiTvce2SKSYN07RCc5:-MX1sbHsEB4gro7zzGQ0:b-jkhw25) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L251)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Wouldn't it be better to rely on RAII and return a `shared_ptr`? Or maybe create `shared_ptr`s at the call sites.
</blockquote></details>

The main issue is that you can't release the `OVERLAPPED` struct nor the data buffer if there is an overlapped operation in progress. There's a special dance to cancel overlapped I/O on sockets correctly, which cannot be performed without considering the socket lifetime and all other pending operations as well.

I'll update the code to be more conformant.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[leaktest/sockutil.cpp, line 255 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWiURFf0vXJiTack8Q7:-MX6m8-MCEKwWaN1gFJg:brxp9sq) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/sockutil.cpp#L255)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`ZeroMemory` is documented as being an alias for `RtlZeroMemory`. So either is fine to use, but for consistency maybe we should always use `ZeroMemory` for user mode code?
</blockquote></details>

Sounds good.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[leaktest/util.cpp, line 93 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWihHHw6bvU-XI-oi8e:-MX6PA8D2b4A2N4me-xU:bet6bti) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L93)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`attributes` could be `std::optional` or a pointer. Then you could just call `LaunchProcessWithAttributes` from `LaunchProcess` to avoid duplicating code.
</blockquote></details>

Well, there's also `STARTUPINFOW` vs `STARTUPINFOEXW` and the associated flag, but you're right.
___
*[leaktest/util.cpp, line 98 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWihqft2F6oBS0sblKq:-MX6OZwo4MCAMp-xN57U:bkzyv9f) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L98)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are these preconditions only expected for `LaunchProcessWithAttributes` and not `LaunchProcess`?
</blockquote></details>

They're most suitably used in all locations. Fixing.
___
*[leaktest/util.cpp, line 287 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWitsG67QP2buJXB7ML:-MX7Gajr2qLbqiPQj9-w:b-pkzycw) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L287)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Won't the list leak if `UpdateProcThreadAttribute` fails?
</blockquote></details>

Yes, fixed.
___
*[leaktest/util.cpp, line 392 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj3FzX8MtJoo34o09C:-MX7GstcEDPYhACAsLH7:b-xyprg8) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/util.cpp#L392)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

s/Ip/Ipv4?
</blockquote></details>

Not necessarily, because using a less specific name lends itself to implementing an overload at a later time (IN6_ADDR).
___
*[leaktest/split-tunnel/st1.cpp, line 199 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj06Mo6lLUKm54nfV_:-MX7J2o2C-lFMGNhQKv0:bt2vr1b) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/split-tunnel/st1.cpp#L199)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should the return value not be checked?
</blockquote></details>

Fixed.
___
*[leaktest/split-tunnel/st1.cpp, line 265 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MWj0USp4NUpX6cLImT3:-MX7OqcQ7CEZSiLAyfE4:bt2vr1b) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/bf5f0e0e7adcc9ec3a945d91c6f4f5595f8eb8fa/leaktest/split-tunnel/st1.cpp#L265)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nitpick (here and elsewhere): Would it make more sense to parse `serverAddr` using `ParseIpv4`, and compare the result to `bindInfo`? Or at least use `IpToString(bindInfo.sin_addr)`.
</blockquote></details>

Fixed.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-:-MX7hzFD1VM2xu47k4vl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[leaktest/sockutil.cpp, line 218 at r2](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MX7i0Lu83lwtm_jEHJx:-MX7c-CA3KXwNcVFfKWr:bcay9my) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e4c823866e3079aef60d19d5965f1c6b801da055/leaktest/sockutil.cpp#L218)):*
> ```cpp
> void DeleteWinsockOverlapped(WinsockOverlapped **ctx)
> {
> 	if ((*ctx)->pendingOperation)
> ```

Could `pendingOperation` be gotten rid of if `hEvent` were simply set to signalled to begin with (since it is manually reset)? Anyway, it doesn't matter.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[leaktest/sockutil.cpp, line 218 at r2](https://reviewable.io/reviews/mullvad/win-split-tunnel/12#-MX7i0Lu83lwtm_jEHJx:-MX7wOrb39B8oMUwyGGh:b-oyydfl) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/e4c823866e3079aef60d19d5965f1c6b801da055/leaktest/sockutil.cpp#L218)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could `pendingOperation` be gotten rid of if `hEvent` were simply set to signalled to begin with (since it is manually reset)? Anyway, it doesn't matter.
</blockquote></details>

No, because then you couldn't inspect a struct instance to know if an operation has completed.

Also, it doesn't solve the larger issue, which is to properly manage overlapped operations in relation to the socket they belong to. For example, the current code right below here uses `WaitForSingleObject` without *knowing* that the operation has been directly or indirectly cancelled.

For production usage, I think the socket would have to be wrapped in a class and that all overlapped operations would have to be registered with the socket instance they belong to.

The complicating rules are:

* For the duration of an overlapped operation, the system owns the `OVERLAPPED` instance and the data buffer.
* If you explicitly cancel an overlapped operation you're not allowed to touch the socket it belongs to.
* If you shut down a socket all overlapped operations are *eventually* cancelled.

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Review by dlon — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

**Pull request merged**
