### PR TITLE
Clarify section on 'development environment'

### PR DESCRIPTION
**Pull request by mvd-ows**
As above.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/14)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[README.md, line 20 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MXgQ1cPzoH3If4U0:-MY9MXgQ1cPzoH3If4U1:b-40dwl9) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L20)):*
> ```Markdown
> The code and project file is known to work with the following combination of software:
> 
> - Visual Studio 2019 (MSVC toolset v14.26)
> ```

I don't think 14.27 has been tried. It might work too.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MjA1Ct8eV7Nzb6wh:-MY9MjA1Ct8eV7Nzb6wi:bacime) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L21)):*
> ```Markdown
> 
> - Visual Studio 2019 (MSVC toolset v14.26)
> - WDK v10.0.18362.1
> ```

Later versions are ok too.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[README.md, line 20 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MXgQ1cPzoH3If4U0:-MY9Rjqo7hJl_chwT07S:b-jlmfcs) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L20)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't think 14.27 has been tried. It might work too.
</blockquote></details>

Possibly.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MjA1Ct8eV7Nzb6wh:-MY9RoL7EmcQAbGIxsHv:b-3wkv3r) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Later versions are ok too.
</blockquote></details>

Maybe. You said you had issues with some WDK header?

This entire section could be reverted, and adding only "don't use MSVC v14.28".

Which approach is better?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[README.md, line 21 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MjA1Ct8eV7Nzb6wh:-MYAPjoKBzzwajXDryhc:bis2174) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L21)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe. You said you had issues with some WDK header?

This entire section could be reverted, and adding only "don't use MSVC v14.28".

Which approach is better?
</blockquote></details>

The header problem was also due to v14.28. It's probably helpful to mention a combination that it is known to work with, so I think it's fine as it is. But it might also be useful to mention that MSVC v14.28 is known *not* to work.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/win-split-tunnel/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[README.md, line 21 at r1](https://reviewable.io/reviews/mullvad/win-split-tunnel/14#-MY9MjA1Ct8eV7Nzb6wh:-MYAV6aqDxdtdYMFy4dv:bz4nhzj) ([raw file](https://github.com/mullvad/win-split-tunnel/blob/d655124a0439a2b854476ff51b433ef4f3a04b52/README.md#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The header problem was also due to v14.28. It's probably helpful to mention a combination that it is known to work with, so I think it's fine as it is. But it might also be useful to mention that MSVC v14.28 is known *not* to work.
</blockquote></details>

That information is already included, below here :tada:

**Pull request merged**
